### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#130]
When using the example https://github.com/keymetrics/pm2-io-apm#usage

When I exit I get:

```
Server express listening on port 3000
^CApplication stopped with code () => {
                        this.io.destroy();
                    } or signal null !
TypeError: cb is not a function
    at MyEntrypoint.onStop (/home/unitech/keymetrics/entrypoint/entrypoint.js:8:5)
    at EventEmitter.io.onExit (/home/unitech/keymetrics/entrypoint/node_modules/@pm2/io/build/main/src/index.js:315:26)
    at EventEmitter.emit (events.js:182:13)
    at EventEmitter.emit (domain.js:442:20)
    at emit (/home/unitech/keymetrics/entrypoint/node_modules/signal-exit/index.js:77:11)
    at process.listener (/home/unitech/keymetrics/entrypoint/node_modules/signal-exit/index.js:91:7)
    at process.emit (events.js:182:13)
    at process.EventEmitter.emit (domain.js:442:20)
```

**Comment by wallet77** [comment]
Done : https://github.com/keymetrics/pm2-io-apm/pull/133
