### ISSUE TITLE
Enhancement: auto delete first line of stacktrace to avoid seeing pmx

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#15]

**Comment by Unitech** [comment]
```
Error: Got a 503
    at Request._callback (/var/www/src/webcheck-worker/worker.js:553:51)
    at Request.self.callback (/var/www/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/var/www/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/var/www/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

not present
