### ISSUE TITLE
 Error: 404 Not Found: @pm2/io@~2.3.11

### ISSUE THREAD

**Issue by sharabiania** [keymetrics/pm2-io-apm#201]
When trying to install `npm install pm2 -g` I I get the following error:

> npm ERR! code E404
npm ERR! 404 Not Found: @pm2/io@~2.3.11
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asharabiani\AppData\Roaming\npm-cache\_logs\2018-09-27T14_50_35_791Z-debug.log

Part of the log file that indicates the error stack:
>115 verbose stack Error: 404 Not Found: @pm2/io@~2.3.11
115 verbose stack     at fetch.then.res (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
115 verbose stack     at tryCatcher (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
115 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
115 verbose stack     at Promise._settlePromise (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
115 verbose stack     at Promise._settlePromise0 (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
115 verbose stack     at Promise._settlePromises (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
115 verbose stack     at Async._drainQueue (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
115 verbose stack     at Async._drainQueues (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
115 verbose stack     at Immediate.Async.drainQueues (C:\Users\asharabiani\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
115 verbose stack     at runCallback (timers.js:794:20)
115 verbose stack     at tryOnImmediate (timers.js:752:5)
115 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by sharabiania** [comment]
sorry wrong place to open the issue. my bad
