### ISSUE TITLE
Exception when transaction tracing is enabled

### ISSUE THREAD

**Issue by JonniK** [keymetrics/pm2-io-apm#207]
Hello, i use pm2 with express app on Heroku and trying to enable transaction tracing.
I use external mLab mongodb if it's meaningfull.
Then transaction tracing is enabled in my pm2/io config i always get this exception:

`TypeError: Illegal invocation
    at Proxy.fallback (/app/node_modules/async-listener/index.js:563:15)
    at executeScram (/app/node_modules/mongodb-core/lib/auth/scram.js:183:24)
    at /app/node_modules/mongodb-core/lib/auth/scram.js:361:7
    at /app/node_modules/async-listener/glue.js:188:31
    at args.(anonymous function) (/app/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
    at process.fallback (/app/node_modules/async-listener/index.js:563:15)`

Without transaction tracing all works fine.
Also on my local machine everithings works fine with enabled transaction tracing too.

How can i fix it?

**Comment by vmarchaud** [comment]
Thanks for the port. It appear the issue come from one of the dependency of the tracing system, if you don't reproduce in development i would advise to try updating your node_modules (i would expect the issue come from the a difference in mongoose version).
If the issue persist, i would simply disable the tracing (we are currently on a new one that would fix the issue)

Regards
