### ISSUE TITLE
bug: standalone without apmOptions

### ISSUE THREAD

**Issue by f-hj** [keymetrics/pm2-io-apm#219]
```js
/Users/florian/github/keymetrics/pm2-io-apm/build/main/transports/WebsocketTransport.js:47
        this.agent.sendLogs = this.config.sendLogs || false;
                                          ^

TypeError: Cannot read property 'sendLogs' of undefined
    at WebsocketTransport.init (/Users/florian/github/keymetrics/pm2-io-apm/build/main/transports/WebsocketTransport.js:47:43)
    at Object.createTransport (/Users/florian/github/keymetrics/pm2-io-apm/build/main/services/transport.js:20:23)
    at PMX.init (/Users/florian/github/keymetrics/pm2-io-apm/build/main/pmx.js:60:38)
    at Object.<anonymous> (/Users/florian/github/keymetrics/pm2-io-apm/mytest.js:3:5)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```

```js
const pmx = require('.')

pmx.init({
  standalone: true,
  tracing: true
})
```

**Comment by Unitech** [comment]
can we close this?

**Comment by Eywek** [comment]
Yes
