### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#223]
- String "Failed to require the profiler via addon, disabling profiling ...\n" is output, it should not
- When doing empty rejection it fails
https://github.com/Unitech/pm2/blob/master/test/fixtures/promise/empty-rejection.js
```
0|empty-rejection  | undefined
0|empty-rejection  | TypeError: Cannot read property 'message' of undefined
0|empty-rejection  |     at process.NotifyFeature.onUnhandledRejection (/home/unitech/keymetrics/pm2/node_modules/@pm2/io/build/main/features/notify.js:83:28)
0|empty-rejection  |     at process.emit (events.js:182:13)
0|empty-rejection  |     at emitPromiseRejectionWarnings (internal/process/promises.js:105:20)
0|empty-rejection  |     at process._tickCallback (internal/process/next_tick.js:69:34)
```

**Comment by vmarchaud** [comment]
Fixed in 3.1.0
