### ISSUE TITLE
with Node 4 issues are swallowed

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#225]
test.js:
```
setTimeout(() => {
  throw new Error('err')
}, 1000)
```

With `pm2 start test.js`:

```
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
0|main     | [Error: errr]
```

With pm2 start test.js --no-pmx:

```
0|main     |     at Timeout._onTimeout (/home/unitech/keymetrics/pm2/test/fixtures/app/main.ts:7:9)
0|main     |     at ontimeout (timers.js:498:11)
0|main     |     at tryOnTimeout (timers.js:323:5)
0|main     |     at Timer.listOnTimeout (timers.js:290:5)
0|main     | Error: errr
0|main     |     at Timeout._onTimeout (/home/unitech/keymetrics/pm2/test/fixtures/app/main.ts:7:9)
0|main     |     at ontimeout (timers.js:498:11)
0|main     |     at tryOnTimeout (timers.js:323:5)
0|main     |     at Timer.listOnTimeout (timers.js:290:5)
0|main     | Error: errr
0|main     |     at null._onTimeout (/home/unitech/keymetrics/pm2/test/fixtures/app/main.ts:7:9)
0|main     |     at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by vmarchaud** [comment]
Which version are you using ?

**Comment by Unitech** [comment]
Node 4.x
