### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ericman314** [keymetrics/pm2-io-apm#276]
When using [workerpool](https://www.npmjs.com/package/workerpool) in node v14.8.0, then about five seconds after running a worker, this error is thrown:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.extractMessagePort (/.../node_modules/event-loop-inspector/utils.js:94:31)
    at /.../node_modules/event-loop-inspector/index.js:45:17
    at Array.forEach (<anonymous>)
    at Object.dump (/.../node_modules/event-loop-inspector/index.js:22:42)
    at Timeout._onTimeout (/.../node_modules/@pm2/io/build/main/transports/IPCTransport.js:34:50)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
```

This bug only occurs _after_ running a worker using workerpool. I also posted the issue over there.

You can use this to test:

### littleFunction.js

```js
const workerpool = require('workerpool')

function littleFunction(a) {
  return -a
}

workerpool.worker({
  littleFunction
})
```

### testLittleFunction.js

```js
const io = require('@pm2/io')
const workerpool = require('workerpool')

const pool = workerpool.pool(__dirname + '/littleFunction.js')

pool.exec('littleFunction', [5]).then(answer => {
  console.log(answer)
}).catch(ex => {
  console.error(ex)
})

// Keep process running long enough for the error to occur
setTimeout(() => { }, 10000)
```

**Comment by ericman314** [comment]
Sorry, turns out I was running an older version of @pm2/io, 4.2.4. In the latest version, 4.3.5, the error does not occur.
